---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: face-recognition-production
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-waf: "true"
    nginx.ingress.kubernetes.io/limit-rpm: "1000"
spec:
  tls:
    - hosts:
        - api.example.com
      secretName: backend-tls-prod
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
