---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: face-recognition-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - staging.example.com
      secretName: backend-tls-staging
  rules:
    - host: staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
