---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1  # Single replica for development
  template:
    spec:
      containers:
        - name: backend
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
              nvidia.com/gpu: 0
            requests:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: DEBUG
              value: "true"
            - name: RELOAD
              value: "true"
