apiVersion: v1
kind: Namespace
metadata:
  name: ai-f
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ai-f
  name: ai-f-reader
rules:
- apiGroups: [\"\"]
  resources: [\"pods/log\", \"services\", \"endpoints\"]
  verbs: [\"get\", \"list\", \"watch\"]
- apiGroups: [\"extensions\", \"apps\"]
  resources: [\"deployments\", \"replicasets\"]
  verbs: [\"get\", \"list\"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-f-readers
  namespace: ai-f
subjects:
- kind: ServiceAccount
  name: ai-f-sa
  namespace: ai-f
roleRef:
  kind: Role
  name: ai-f-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-f-sa
  namespace: ai-f
