backend:
  replicaCount: 1
  gpu: false
  resources:
    limits:
      cpu: 2
      memory: 4Gi
redis:
  password: "devpass"
postgres:
  password: "devpass"
ingress:
  enabled: true
  hosts:
    - host: ai-f.local
hpa:
  backend:
    minReplicas: 1
