# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import face_recognition_pb2 as app_dot_grpc_dot_face__recognition__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc/face_recognition_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceRecognitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/Enroll',
                request_serializer=app_dot_grpc_dot_face__recognition__pb2.EnrollRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_face__recognition__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.Recognize = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/Recognize',
                request_serializer=app_dot_grpc_dot_face__recognition__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_face__recognition__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.GetPerson = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/GetPerson',
                request_serializer=app_dot_grpc_dot_face__recognition__pb2.GetPersonRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_face__recognition__pb2.PersonResponse.FromString,
                _registered_method=True)
        self.DeletePerson = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/DeletePerson',
                request_serializer=app_dot_grpc_dot_face__recognition__pb2.DeletePersonRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_face__recognition__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.GetAuditLogs = channel.unary_unary(
                '/face_recognition.FaceRecognitionService/GetAuditLogs',
                request_serializer=app_dot_grpc_dot_face__recognition__pb2.AuditLogsRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_face__recognition__pb2.AuditLogsResponse.FromString,
                _registered_method=True)


class FaceRecognitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=app_dot_grpc_dot_face__recognition__pb2.EnrollRequest.FromString,
                    response_serializer=app_dot_grpc_dot_face__recognition__pb2.EnrollResponse.SerializeToString,
            ),
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=app_dot_grpc_dot_face__recognition__pb2.RecognizeRequest.FromString,
                    response_serializer=app_dot_grpc_dot_face__recognition__pb2.RecognizeResponse.SerializeToString,
            ),
            'GetPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPerson,
                    request_deserializer=app_dot_grpc_dot_face__recognition__pb2.GetPersonRequest.FromString,
                    response_serializer=app_dot_grpc_dot_face__recognition__pb2.PersonResponse.SerializeToString,
            ),
            'DeletePerson': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePerson,
                    request_deserializer=app_dot_grpc_dot_face__recognition__pb2.DeletePersonRequest.FromString,
                    response_serializer=app_dot_grpc_dot_face__recognition__pb2.DeleteResponse.SerializeToString,
            ),
            'GetAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLogs,
                    request_deserializer=app_dot_grpc_dot_face__recognition__pb2.AuditLogsRequest.FromString,
                    response_serializer=app_dot_grpc_dot_face__recognition__pb2.AuditLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face_recognition.FaceRecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('face_recognition.FaceRecognitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceRecognitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/Enroll',
            app_dot_grpc_dot_face__recognition__pb2.EnrollRequest.SerializeToString,
            app_dot_grpc_dot_face__recognition__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/Recognize',
            app_dot_grpc_dot_face__recognition__pb2.RecognizeRequest.SerializeToString,
            app_dot_grpc_dot_face__recognition__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/GetPerson',
            app_dot_grpc_dot_face__recognition__pb2.GetPersonRequest.SerializeToString,
            app_dot_grpc_dot_face__recognition__pb2.PersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/DeletePerson',
            app_dot_grpc_dot_face__recognition__pb2.DeletePersonRequest.SerializeToString,
            app_dot_grpc_dot_face__recognition__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/face_recognition.FaceRecognitionService/GetAuditLogs',
            app_dot_grpc_dot_face__recognition__pb2.AuditLogsRequest.SerializeToString,
            app_dot_grpc_dot_face__recognition__pb2.AuditLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
